In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [5]:
a=pd.read_excel("Data_Train.xlsx")
d_test=pd.read_excel("Data_Test.xlsx")

In [196]:
d_test.head()

Title                  Author  \
0         The Complete Sherlock Holmes: 2 Boxes sets  Sir Arthur Conan Doyle   
1  Learn Docker - Fundamentals of Docker 18.x: Ev...     Gabriel N. Schenker   
2                                           Big Girl          Danielle Steel   
3  Think Python: How to Think Like a Computer Sci...         Allen B. Downey   
4  Oxford Word Skills: Advanced - Idioms & Phrasa...           Redman Gairns   

                              Edition  Reviews  Ratings  \
0  Mass Market Paperback,– 1 Oct 1986      4.4    960.0   
1     Paperback,– Import, 26 Apr 2018      5.0      1.0   
2             Paperback,– 17 Mar 2011      5.0      4.0   
3                    Paperback,– 2016      4.1     11.0   
4             Paperback,– 26 Dec 2011      4.4      9.0   

                                            Synopsis  \
0  A collection of entire body of work of the She...   
1  Enhance your software deployment workflow usin...   
2  'Watch out, world. Here I come!'\nFor Victoria...   
3  If you want to learn how to program, working w...   
4  Learn and practise the verbs, prepositions and...   

                                        Genre  \
0                       Short Stories (Books)   
1                 Operating Systems Textbooks   
2                             Romance (Books)   
3  Programming & Software Development (Books)   
4                         Linguistics (Books)   

                          BookCategory  
0            Crime, Thriller & Mystery  
1  Computing, Internet & Digital Media  
2                              Romance  
3  Computing, Internet & Digital Media  
4      Language, Linguistics & Writing

In [6]:
a.head()

Title           Author  \
0         The Prisoner's Gold (The Hunters 3)   Chris Kuzneski   
1          Guru Dutt: A Tragedy in Three Acts     Arun Khopkar   
2                Leviathan (Penguin Classics)    Thomas Hobbes   
3          A Pocket Full of Rye (Miss Marple)  Agatha Christie   
4  LIFE 70 Years of Extraordinary Photography  Editors of Life   

                   Edition             Reviews              Ratings  \
0  Paperback,– 10 Mar 2016  4.0 out of 5 stars   8 customer reviews   
1   Paperback,– 7 Nov 2012  3.9 out of 5 stars  14 customer reviews   
2  Paperback,– 25 Feb 1982  4.8 out of 5 stars   6 customer reviews   
3   Paperback,– 5 Oct 2017  4.1 out of 5 stars  13 customer reviews   
4  Hardcover,– 10 Oct 2006  5.0 out of 5 stars    1 customer review   

                                            Synopsis  \
0  THE HUNTERS return in their third brilliant no...   
1  A layered portrait of a troubled genius for wh...   
2  "During the time men live without a common Pow...   
3  A handful of grain is found in the pocket of a...   
4  For seven decades, "Life" has been thrilling t...   

                          Genre                          BookCategory   Price  
0    Action & Adventure (Books)                    Action & Adventure  220.00  
1    Cinema & Broadcast (Books)  Biographies, Diaries & True Accounts  202.93  
2       International Relations                                Humour  299.00  
3  Contemporary Fiction (Books)             Crime, Thriller & Mystery  180.00  
4         Photography Textbooks              Arts, Film & Photography  965.62

In [7]:
a.shape

(6237, 9)

In [8]:
d_test.shape

(1560, 8)

In [43]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6237 entries, 0 to 6236
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Title         6237 non-null   object 
 1   Author        6237 non-null   object 
 2   Edition       6237 non-null   object 
 3   Reviews       6237 non-null   float64
 4   Ratings       6237 non-null   float64
 5   Synopsis      6237 non-null   object 
 6   Genre         6237 non-null   object 
 7   BookCategory  6237 non-null   object 
 8   Price         6237 non-null   float64
dtypes: float64(3), object(6)
memory usage: 438.7+ KB


In [34]:
a["Reviews"]=a.Reviews.apply(lambda r:float(r.split()[0]))


AttributeError: 'float' object has no attribute 'split'

In [93]:
d_test["Reviews"]=d_test.Reviews.apply(lambda r:float(r.split()[0]))


In [40]:
a["Ratings"].head()

0     8.0
1    14.0
2     6.0
3    13.0
4     1.0
Name: Ratings, dtype: float64

In [38]:
a["Ratings"]=a.Ratings.str.extract('(\d+)')
a["Ratings"]=a.Ratings.astype(float)

In [94]:
d_test["Ratings"]=d_test.Ratings.str.extract('(\d+)')
d_test["Ratings"]=d_test.Ratings.astype(float)

In [42]:
data=pd.get_dummies(a,columns=["BookCategory"])
data.head()

Title           Author  \
0         The Prisoner's Gold (The Hunters 3)   Chris Kuzneski   
1          Guru Dutt: A Tragedy in Three Acts     Arun Khopkar   
2                Leviathan (Penguin Classics)    Thomas Hobbes   
3          A Pocket Full of Rye (Miss Marple)  Agatha Christie   
4  LIFE 70 Years of Extraordinary Photography  Editors of Life   

                   Edition  Reviews  Ratings  \
0  Paperback,– 10 Mar 2016      4.0      8.0   
1   Paperback,– 7 Nov 2012      3.9     14.0   
2  Paperback,– 25 Feb 1982      4.8      6.0   
3   Paperback,– 5 Oct 2017      4.1     13.0   
4  Hardcover,– 10 Oct 2006      5.0      1.0   

                                            Synopsis  \
0  THE HUNTERS return in their third brilliant no...   
1  A layered portrait of a troubled genius for wh...   
2  "During the time men live without a common Pow...   
3  A handful of grain is found in the pocket of a...   
4  For seven decades, "Life" has been thrilling t...   

                          Genre   Price  BookCategory_Action & Adventure  \
0    Action & Adventure (Books)  220.00                                1   
1    Cinema & Broadcast (Books)  202.93                                0   
2       International Relations  299.00                                0   
3  Contemporary Fiction (Books)  180.00                                0   
4         Photography Textbooks  965.62                                0   

   BookCategory_Arts, Film & Photography  \
0                                      0   
1                                      0   
2                                      0   
3                                      0   
4                                      1   

   BookCategory_Biographies, Diaries & True Accounts  \
0                                                  0   
1                                                  1   
2                                                  0   
3                                                  0   
4                                                  0   

   BookCategory_Comics & Mangas  \
0                             0   
1                             0   
2                             0   
3                             0   
4                             0   

   BookCategory_Computing, Internet & Digital Media  \
0                                                 0   
1                                                 0   
2                                                 0   
3                                                 0   
4                                                 0   

   BookCategory_Crime, Thriller & Mystery  BookCategory_Humour  \
0                                       0                    0   
1                                       0                    0   
2                                       0                    1   
3                                       1                    0   
4                                       0                    0   

   BookCategory_Language, Linguistics & Writing  BookCategory_Politics  \
0                                             0                      0   
1                                             0                      0   
2                                             0                      0   
3                                             0                      0   
4                                             0                      0   

   BookCategory_Romance  BookCategory_Sports  
0                     0                    0  
1                     0                    0  
2                     0                    0  
3                     0                    0  
4                     0                    0

In [95]:
test=pd.get_dummies(a,columns=["BookCategory"])

In [46]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6237 entries, 0 to 6236
Data columns (total 14 columns):
 #   Column                                             Non-Null Count  Dtype  
---  ------                                             --------------  -----  
 0   Reviews                                            6237 non-null   float64
 1   Ratings                                            6237 non-null   float64
 2   Price                                              6237 non-null   float64
 3   BookCategory_Action & Adventure                    6237 non-null   uint8  
 4   BookCategory_Arts, Film & Photography              6237 non-null   uint8  
 5   BookCategory_Biographies, Diaries & True Accounts  6237 non-null   uint8  
 6   BookCategory_Comics & Mangas                       6237 non-null   uint8  
 7   BookCategory_Computing, Internet & Digital Media   6237 non-null   uint8  
 8   BookCategory_Crime, Thriller & Mystery             6237 non-null   uint8  
 9   BookCate

In [195]:
test.head()

Reviews  Ratings   Price  BookCategory_Action & Adventure  \
0      4.0      8.0  220.00                                1   
1      3.9     14.0  202.93                                0   
2      4.8      6.0  299.00                                0   
3      4.1     13.0  180.00                                0   
4      5.0      1.0  965.62                                0   

   BookCategory_Arts, Film & Photography  \
0                                      0   
1                                      0   
2                                      0   
3                                      0   
4                                      1   

   BookCategory_Biographies, Diaries & True Accounts  \
0                                                  0   
1                                                  1   
2                                                  0   
3                                                  0   
4                                                  0   

   BookCategory_Comics & Mangas  \
0                             0   
1                             0   
2                             0   
3                             0   
4                             0   

   BookCategory_Computing, Internet & Digital Media  \
0                                                 0   
1                                                 0   
2                                                 0   
3                                                 0   
4                                                 0   

   BookCategory_Crime, Thriller & Mystery  BookCategory_Humour  \
0                                       0                    0   
1                                       0                    0   
2                                       0                    1   
3                                       1                    0   
4                                       0                    0   

   BookCategory_Language, Linguistics & Writing  BookCategory_Politics  \
0                                             0                      0   
1                                             0                      0   
2                                             0                      0   
3                                             0                      0   
4                                             0                      0   

   BookCategory_Romance  BookCategory_Sports  
0                     0                    0  
1                     0                    0  
2                     0                    0  
3                     0                    0  
4                     0                    0

In [200]:
d_test=pd.get_dummies(d_test,columns=["BookCategory"])

In [201]:
d_test.head()

Reviews  Ratings  BookCategory_Action & Adventure  \
0      4.4    960.0                                0   
1      5.0      1.0                                0   
2      5.0      4.0                                0   
3      4.1     11.0                                0   
4      4.4      9.0                                0   

   BookCategory_Arts, Film & Photography  \
0                                      0   
1                                      0   
2                                      0   
3                                      0   
4                                      0   

   BookCategory_Biographies, Diaries & True Accounts  \
0                                                  0   
1                                                  0   
2                                                  0   
3                                                  0   
4                                                  0   

   BookCategory_Comics & Mangas  \
0                             0   
1                             0   
2                             0   
3                             0   
4                             0   

   BookCategory_Computing, Internet & Digital Media  \
0                                                 0   
1                                                 1   
2                                                 0   
3                                                 1   
4                                                 0   

   BookCategory_Crime, Thriller & Mystery  BookCategory_Humour  \
0                                       1                    0   
1                                       0                    0   
2                                       0                    0   
3                                       0                    0   
4                                       0                    0   

   BookCategory_Language, Linguistics & Writing  BookCategory_Politics  \
0                                             0                      0   
1                                             0                      0   
2                                             0                      0   
3                                             0                      0   
4                                             1                      0   

   BookCategory_Romance  BookCategory_Sports  
0                     0                    0  
1                     0                    0  
2                     1                    0  
3                     0                    0  
4                     0                    0

In [198]:
d_test = d_test.drop(['Title','Genre', 'Author','Synopsis','Edition'],1, inplace= False)


C:\Users\pavan\AppData\Local\Temp\ipykernel_14936\3894091484.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  d_test = d_test.drop(['Title','Genre', 'Author','Synopsis','Edition'],1, inplace= False)


In [47]:
data = data.drop(['Title','Genre', 'Author','Synopsis','Edition'],1, inplace= False)


C:\Users\pavan\AppData\Local\Temp\ipykernel_14936\659449508.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  data = data.drop(['Title','Genre', 'Author','Synopsis','Edition'],1, inplace= False)


KeyError: "['Title', 'Genre', 'Author', 'Synopsis', 'Edition'] not found in axis"

In [96]:
test = test.drop(['Title','Genre', 'Author','Synopsis','Edition'],1, inplace= False)


C:\Users\pavan\AppData\Local\Temp\ipykernel_14936\642810392.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  test = test.drop(['Title','Genre', 'Author','Synopsis','Edition'],1, inplace= False)


In [13]:
a.describe

<bound method NDFrame.describe of                                                   Title           Author  \
0                   The Prisoner's Gold (The Hunters 3)   Chris Kuzneski   
1                    Guru Dutt: A Tragedy in Three Acts     Arun Khopkar   
2                          Leviathan (Penguin Classics)    Thomas Hobbes   
3                    A Pocket Full of Rye (Miss Marple)  Agatha Christie   
4            LIFE 70 Years of Extraordinary Photography  Editors of Life   
...                                                 ...              ...   
6232  Humans: A Brief History of How We F*cked It Al...     Tom Phillips   
6233                                        The Chemist  Stephenie Meyer   
6234  The Duke And I: Number 1 in series (Bridgerton...      Julia Quinn   
6235                       Frostfire (Kanin Chronicles)   Amanda Hocking   
6236                        The First Order (Sam Capra)      Jeff Abbott   

                      Edition             Reviews    

In [133]:
data["Price"]

0       220.00
1       202.93
2       299.00
3       180.00
4       965.62
         ...  
6232    322.00
6233    421.00
6234    399.00
6235    319.00
6236    452.00
Name: Price, Length: 6237, dtype: float64

In [138]:
y

array([[220.  ],
       [202.93],
       [299.  ],
       ...,
       [399.  ],
       [319.  ],
       [452.  ]])

In [136]:
y=np.array(data["Price"]).reshape(-1,1)
x=data.drop("Price",axis=1)
x.shape

(6237, 13)

In [132]:
x.head()

Reviews  Ratings  BookCategory_Action & Adventure  \
0      4.0      8.0                                1   
1      3.9     14.0                                0   
2      4.8      6.0                                0   
3      4.1     13.0                                0   
4      5.0      1.0                                0   

   BookCategory_Arts, Film & Photography  \
0                                      0   
1                                      0   
2                                      0   
3                                      0   
4                                      1   

   BookCategory_Biographies, Diaries & True Accounts  \
0                                                  0   
1                                                  1   
2                                                  0   
3                                                  0   
4                                                  0   

   BookCategory_Comics & Mangas  \
0                             0   
1                             0   
2                             0   
3                             0   
4                             0   

   BookCategory_Computing, Internet & Digital Media  \
0                                                 0   
1                                                 0   
2                                                 0   
3                                                 0   
4                                                 0   

   BookCategory_Crime, Thriller & Mystery  BookCategory_Humour  \
0                                       0                    0   
1                                       0                    0   
2                                       0                    1   
3                                       1                    0   
4                                       0                    0   

   BookCategory_Language, Linguistics & Writing  BookCategory_Politics  \
0                                             0                      0   
1                                             0                      0   
2                                             0                      0   
3                                             0                      0   
4                                             0                      0   

   BookCategory_Romance  BookCategory_Sports  
0                     0                    0  
1                     0                    0  
2                     0                    0  
3                     0                    0  
4                     0                    0

In [48]:
data.corr()

Reviews   Ratings  \
Reviews                                            1.000000 -0.009644   
Ratings                                           -0.009644  1.000000   
Price                                              0.108373 -0.101145   
BookCategory_Action & Adventure                    0.009149 -0.003412   
BookCategory_Arts, Film & Photography              0.039866 -0.052676   
BookCategory_Biographies, Diaries & True Accounts  0.016837  0.162393   
BookCategory_Comics & Mangas                       0.092094 -0.058998   
BookCategory_Computing, Internet & Digital Media  -0.026881 -0.045564   
BookCategory_Crime, Thriller & Mystery            -0.080658  0.040833   
BookCategory_Humour                                0.026311 -0.057393   
BookCategory_Language, Linguistics & Writing      -0.057767 -0.013023   
BookCategory_Politics                             -0.013167  0.028476   
BookCategory_Romance                              -0.041818  0.055138   
BookCategory_Sports                                0.044611 -0.066637   

                                                      Price  \
Reviews                                            0.108373   
Ratings                                           -0.101145   
Price                                              1.000000   
BookCategory_Action & Adventure                   -0.081581   
BookCategory_Arts, Film & Photography              0.118747   
BookCategory_Biographies, Diaries & True Accounts -0.101540   
BookCategory_Comics & Mangas                       0.089171   
BookCategory_Computing, Internet & Digital Media   0.175736   
BookCategory_Crime, Thriller & Mystery            -0.117213   
BookCategory_Humour                                0.041757   
BookCategory_Language, Linguistics & Writing      -0.046355   
BookCategory_Politics                             -0.013901   
BookCategory_Romance                              -0.093160   
BookCategory_Sports                                0.074360   

                                                   BookCategory_Action & Adventure  \
Reviews                                                                   0.009149   
Ratings                                                                  -0.003412   
Price                                                                    -0.081581   
BookCategory_Action & Adventure                                           1.000000   
BookCategory_Arts, Film & Photography                                    -0.116806   
BookCategory_Biographies, Diaries & True Accounts                        -0.126288   
BookCategory_Comics & Mangas                                             -0.124759   
BookCategory_Computing, Internet & Digital Media                         -0.115941   
BookCategory_Crime, Thriller & Mystery                                   -0.140687   
BookCategory_Humour                                                      -0.119616   
BookCategory_Language, Linguistics & Writing                             -0.126054   
BookCategory_Politics                                                    -0.091094   
BookCategory_Romance                                                     -0.122026   
BookCategory_Sports                                                      -0.111043   

                                                   BookCategory_Arts, Film & Photography  \
Reviews                                                                         0.039866   
Ratings                                                                        -0.052676   
Price                                                                           0.118747   
BookCategory_Action & Adventure                                                -0.116806   
BookCategory_Arts, Film & Photography                                           1.000000   
BookCategory_Biographies, Diaries & True Accounts                              -0.097722   
BookCategory_Comics & Mangas                                               

In [20]:
from sklearn.model_selection import train_test_split

In [139]:
x_train, x_test, y_train, y_test= train_test_split(x,y,test_size=0.2)

In [140]:
from sklearn.preprocessing import StandardScaler

In [141]:
scaler=StandardScaler()

In [142]:
scaler.fit(y_train)

StandardScaler()

In [144]:
scaler.transform(y_train)

array([[-0.26139555],
       [-0.53456938],
       [ 0.03661227],
       ...,
       [-0.50007773],
       [ 2.6745333 ],
       [ 1.08515829]])

In [109]:
scaler.fit(x_train,y_train)

StandardScaler()

In [122]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4989 entries, 1907 to 3771
Data columns (total 13 columns):
 #   Column                                             Non-Null Count  Dtype  
---  ------                                             --------------  -----  
 0   Reviews                                            4989 non-null   float64
 1   Ratings                                            4989 non-null   float64
 2   BookCategory_Action & Adventure                    4989 non-null   uint8  
 3   BookCategory_Arts, Film & Photography              4989 non-null   uint8  
 4   BookCategory_Biographies, Diaries & True Accounts  4989 non-null   uint8  
 5   BookCategory_Comics & Mangas                       4989 non-null   uint8  
 6   BookCategory_Computing, Internet & Digital Media   4989 non-null   uint8  
 7   BookCategory_Crime, Thriller & Mystery             4989 non-null   uint8  
 8   BookCategory_Humour                                4989 non-null   uint8  
 9   BookC

In [123]:
y_train.info()

<class 'pandas.core.series.Series'>
Int64Index: 4989 entries, 1907 to 3771
Series name: Price
Non-Null Count  Dtype  
--------------  -----  
4989 non-null   float64
dtypes: float64(1)
memory usage: 78.0 KB


In [124]:
tree.fit(x_train,y_train)

RandomForestRegressor()

In [126]:
tree.predict(x_test)

array([ 431.99619048,  289.97666667,  718.81546093, ..., 1282.47219752,
        580.31918246,  878.00964838])

In [62]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.feature_selection import SelectFromModel

In [85]:
model=LinearRegression()
tree=RandomForestRegressor()

In [128]:
model.fit(x_train,y_train)

LinearRegression()

In [146]:
model.predict(x_test)

array([673.20069865, 855.76525602, 568.11037018, ..., 536.60667094,
       545.29948571, 809.63286024])

In [147]:
y_test

array([[ 90.  ],
       [367.  ],
       [573.18],
       ...,
       [625.  ],
       [202.  ],
       [599.  ]])

In [130]:
x_train

Reviews  Ratings  BookCategory_Action & Adventure  \
1907      4.3      5.0                                1   
6167      3.7    113.0                                1   
2487      5.0      4.0                                0   
2378      4.7     37.0                                0   
2603      4.0     14.0                                0   
...       ...      ...                              ...   
5591      4.1     27.0                                0   
1046      5.0      1.0                                0   
4262      4.5      2.0                                0   
3740      4.6     12.0                                0   
3771      4.8      6.0                                0   

      BookCategory_Arts, Film & Photography  \
1907                                      0   
6167                                      0   
2487                                      0   
2378                                      0   
2603                                      1   
...                                     ...   
5591                                      0   
1046                                      0   
4262                                      0   
3740                                      0   
3771                                      0   

      BookCategory_Biographies, Diaries & True Accounts  \
1907                                                  0   
6167                                                  0   
2487                                                  0   
2378                                                  0   
2603                                                  0   
...                                                 ...   
5591                                                  0   
1046                                                  0   
4262                                                  0   
3740                                                  0   
3771                                                  0   

      BookCategory_Comics & Mangas  \
1907                             0   
6167                             0   
2487                             0   
2378                             0   
2603                             0   
...                            ...   
5591                             0   
1046                             0   
4262                             0   
3740                             1   
3771                             1   

      BookCategory_Computing, Internet & Digital Media  \
1907                                                 0   
6167                                                 0   
2487                                                 0   
2378                                                 0   
2603                                                 0   
...                                                ...   
5591                                                 0   
1046                                                 1   
4262                                                 0   
3740                                                 0   
3771                                                 0   

      BookCategory_Crime, Thriller & Mystery  BookCategory_Humour  \
1907                                       0                    0   
6167                                       0                    0   
2487                                       0                    0   
2378                                       0                    0   
2603                                       0                    0   
...                                      ...                  ...   
5591                                       0                    0   
1046                                       0                    0   
4262                                       0                    0   
3740                                       0                    0   
3771                                       0                    0   

      BookCategory_Language, Linguistics

In [86]:
tree.fit(x_train,y_train)

RandomForestRegressor()

In [120]:
y_train.head()

1907     358.0
6167     310.0
2487     369.0
2378     474.0
2603    1699.0
Name: Price, dtype: float64

In [157]:
pred=tree.predict(x_train)
pred

array([313.74833333, 245.3868    , 485.94873333, ..., 161.4985    ,
       923.1339583 , 925.98140476])

In [163]:
r2_score(y_train,pred)

0.2999607691116405

In [160]:
data=pd.DataFrame(y_train,pred)

In [162]:
data

0
313.748333    383.0
245.386800    185.0
485.948733    599.0
248.323700    262.0
1282.472198  1200.0
...             ...
365.620198    100.0
299.850000    224.0
161.498500    210.0
923.133958   2511.0
925.981405   1359.0

[4989 rows x 1 columns]

In [64]:
sfm = SelectFromModel(model)

In [54]:
model.fit(x_train,y_train)

LinearRegression()

In [74]:
from sklearn.preprocessing import PowerTransformer

In [75]:
power=PowerTransformer()

In [82]:
power.fit(x_train,y_train)

PowerTransformer()

In [185]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 500, random_state = 300)
regressor.fit(x_train, y_train)

C:\Users\pavan\AppData\Local\Temp\ipykernel_14936\3335631100.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  regressor.fit(x_train, y_train)


RandomForestRegressor(n_estimators=500, random_state=300)

In [193]:
y_pred = regressor.predict(x_train)
y_pred

array([351.766     , 215.8991381 , 524.38844   , ..., 192.97748571,
       925.53073607, 871.99404476])

In [194]:
r2_score(y_train,y_pred)

0.40397137471699074

In [203]:
ypre=regressor.predict(d_test)

In [204]:
ypre = pd.DataFrame(ypre)

In [206]:
ypre = ypre.rename(columns= {0:"Price"})

In [207]:
ypre.to_csv("Submission.csv")

In [209]:
cs=pd.read_excel("Sample_Submission.xlsx")

In [210]:
cs.head()

Price
0    119
1    123
2    108
3    118
4    132